{
 "title": "Web App",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "App info",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_info" }
   ]
  },
  {
   "title": "Total visits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"get\"})"
    }
   ]
  },
  {
   "title": "Home visits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"get\", endpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "app_errors_total" }
   ]
  },
  {
   "title": "Home page last visit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "first",
   "targets": [
    {
     "expr": "app_last_visit_time_seconds{endpoint=\"/\"}*1000"
    }
   ]
  },
  {
   "title": "Last visit",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "app_last_visit_time_seconds{}*1000"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "app_requests_total{method=\"get\"}"
    }
   ]
  },
  {
   "title": "Page visits/s ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_requests_total{method=\"get\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Page latency in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_page_latency_seconds_sum[1m])/rate(app_page_latency_seconds_count[1m])",
     "legendFormat": "/summary"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"app:8000\",job=\"web-apps\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"app:8000\", job=\"web-apps\"}"
    }
   ]
  }
 ]
}